celeba64_config=\
    {
    "attn_resolutions": [16],
    "batch_size": 32,
    "beta1": 0.0,
    "beta2": 0.9,
    "beta_max": 20.0,
    "beta_min": 0.1,
    "centered": True,
    "network_type": 'ncsnpp',
    "ch_mult": [
        1,
        1,
        2,
        2,
        4
    ],
    "conditional": True,
    "dataset": "celeba64",
    "dropout": 0.1,
    "ema_decay": 0.999,
    "embedding_type": "positional",
    "exp": "experiment_cifar_exp1",
    "fir": True,
    "fir_kernel": [
        1,
        3,
        3,
        1
    ],
    "fourier_scale": 16.0,
    "global_rank": 0,
    "image_size": 64,
    "local_rank": 0,
    "lr_d": 5e-05,
    "lr_g": 5e-05,
    "master_address": "127.0.0.2",
    "n_mlp": 4,
    "ngf": 64,
    "no_lr_decay": False,
    "node_rank": 0,
    "not_use_tanh": False,
    "num_channels": 3,
    "num_channels_dae": 64,
    "num_epoch": 600,
    "num_proc_node": 1,
    "num_process_per_node": 1,
    "num_res_blocks": 2,
    "num_res_blocks_E": 2,
    "num_timesteps": 4,
    "nz": 100,
    "progressive": "none",
    "progressive_combine": "sum",
    "progressive_input": "residual",
    "r1_gamma": 0.002,
    "resamp_with_conv": True,
    "resblock_type": "biggan",
    "resume": False,
    "save_ckpt_every": 50,
    "save_content": True,
    "save_content_every": 50,
    "seed": 2338,
    "skip_rescale": True,
    "t_emb_dim": 256,
    "use_ema": True,
    "use_geometric": False,
    "world_size": 4,
    "z_emb_dim": 256
}